import { GlassCard, ExpandableCard, Badge, Button, ModelLimitErrorBanner, Tooltip } from '@/components/common';
import { useOrgInfoRecommendationsStore } from '@/store/slices/orgInfoRecommendationsStore';
import { useVSCode } from '@/hooks/useVSCode';
import { DEMO_ORG_INFO_RECOMMENDATIONS } from './sampleData';
import type { AnalysisResult, OrgInfoImpact, OrgInfoRecommendationCard } from '@/types';

interface Props {
  results: AnalysisResult | null;
}

const IMPACT_VARIANT: Record<OrgInfoImpact, 'warning' | 'info' | 'default'> = {
  High: 'warning',
  Medium: 'info',
  Low: 'default',
  Insight: 'default',
};

const ICON_BG: Record<string, string> = {
  'license-utilization': 'rgba(59,130,246,.15)',
  'storage-headroom': 'rgba(236,72,153,.15)',
  'cloud-adoption': 'rgba(20,184,166,.15)',
  'integration-footprint': 'rgba(139,92,246,.15)',
  'platform-currency': 'rgba(245,158,11,.15)',
};

function fmt(n: number | string): string {
  return typeof n === 'number' ? n.toLocaleString() : n;
}

function RecommendationCard({ card }: { card: OrgInfoRecommendationCard }) {
  const hasEvidence = !!card.evidencePoints && card.evidencePoints.length > 0;
  return (
    <ExpandableCard
      dense
      sample={card.sample}
      expandLabel="View details"
      summary={
        <div className="flex flex-col gap-1.5">
          <div className="flex items-center justify-between gap-2">
            <div className="w-7 h-7 rounded-lg flex items-center justify-center text-sm shrink-0" style={{ background: ICON_BG[card.id] }}>
              {card.icon}
            </div>
            <Badge variant={IMPACT_VARIANT[card.impact]}>{card.impact === 'Insight' ? 'Insight' : `${card.impact} Impact`}</Badge>
          </div>
          <span className="text-[10px] font-semibold text-sf-text leading-tight">{card.title}</span>
          <span className="text-xl font-bold text-sf-text tabular-nums">{fmt(card.value)}</span>
          <span className="text-[11px] text-sf-muted leading-tight">{card.valueLabel}</span>
          <div className="pt-1.5 mt-0.5 border-t border-sf-border/50">
            <span className="text-[10px] text-sf-muted block">{card.detailLabel}</span>
            {card.detailValue && <span className="text-sm font-bold text-sf-text">{card.detailValue}</span>}
          </div>
        </div>
      }
      details={
        hasEvidence ? (
          <ul className="space-y-1.5">
            {card.evidencePoints!.map((p, i) => (
              <li key={i} className="text-[11px] text-sf-text-2 leading-relaxed">
                {p.text}
                {p.evidence && p.evidence.length > 0 && (
                  <div className="mt-0.5 text-[10px] text-sf-muted italic">“{p.evidence[0]}”</div>
                )}
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-[11px] text-sf-muted">
            Generate the AI narrative above for evidence-cited reasoning behind this recommendation.
          </p>
        )
      }
    />
  );
}

export default function OrgInfoRecommendations({ results }: Props) {
  const storeReport = useOrgInfoRecommendationsStore((s) => s.report);
  const loading = useOrgInfoRecommendationsStore((s) => s.loading);
  const error = useOrgInfoRecommendationsStore((s) => s.error);
  const { postMessage } = useVSCode();

  const report = storeReport ?? results?.orgInfoRecommendations ?? null;
  const cards = report?.cards ?? DEMO_ORG_INFO_RECOMMENDATIONS;
  const isAi = !!report?.modelUsed;
  const hasNarrative = cards.some((c) => !!c.evidencePoints?.length);

  return (
    <GlassCard>
      <div className="flex items-center justify-between gap-3 flex-wrap mb-3">
        <div className="flex items-center gap-2">
          <h3 className="text-xs font-semibold text-sf-text">AI Recommendations</h3>
          <Tooltip content="Card values are computed deterministically by OrgPulse from real org data; the narrative text is AI-authored once generated.">
            <span className="text-[10px] text-sf-muted cursor-help">ⓘ</span>
          </Tooltip>
          <span className={isAi ? 'px-1.5 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-wide bg-purple-500/20 text-purple-400' : 'px-1.5 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-wide bg-sf-bg-3 text-sf-muted'}>
            {isAi ? 'AI' : 'Beta'}
          </span>
          {report?.modelUsed && (
            <span className="px-2 py-0.5 rounded-full border border-sf-accent/30 bg-sf-accent/10 text-[10px] font-semibold text-sf-accent">
              Generated by {report.modelUsed}
            </span>
          )}
        </div>
        <Button
          variant="primary"
          size="sm"
          loading={loading}
          onClick={() => postMessage({ command: 'runOrgInfoRecommendations', force: hasNarrative })}
        >
          {hasNarrative ? 'Regenerate' : 'Generate AI Narrative'}
        </Button>
      </div>

      {error && (
        <div className="mb-3">
          <ModelLimitErrorBanner
            message={error}
            onRetry={() => postMessage({ command: 'runOrgInfoRecommendations', force: hasNarrative })}
          />
        </div>
      )}

      <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">
        {cards.map((card) => (
          <RecommendationCard key={card.id} card={card} />
        ))}
      </div>
    </GlassCard>
  );
}
