import { useEffect, useState } from 'react';
import { Badge, GlassCard, Pagination } from '@/components/common';
import SegmentedTabs from '@/components/common/SegmentedTabs';
import { PAGE_SIZE } from '@/constants/severity';
import { cn } from '@/lib/cn';
import type { ArchitectRecommendationSection, RecommendationPriority } from '@/types';

interface Props {
  /** AI-authored sections — undefined until the model has been run for this scope. */
  sections?: ArchitectRecommendationSection[];
  /** Always-available deterministic sections, shown until (or if) AI sections exist. */
  fallbackSections: ArchitectRecommendationSection[];
  loading?: boolean;
  className?: string;
  /** Concrete model name/id that generated `sections`, e.g. "Claude Opus 4.8". */
  modelUsed?: string;
  /** Prose narrative summary — AI-authored (pack.narrative.summary) or a deterministic fallback sentence. */
  summary?: string;
  /** Total estimated effort (hours) to close all current gaps. */
  effortHours?: number;
}

const PRIORITY_VARIANT: Record<RecommendationPriority, 'error' | 'warning' | 'info' | 'default'> = {
  Critical: 'error',
  High: 'warning',
  Medium: 'info',
  Low: 'default',
};

/**
 * Generic "Architect Recommendations" panel: evidence-cited pointers grouped into
 * sections, like a real CTA report. Reused across Future Readiness packs today; intended
 * for reuse by other dashboard tabs in a later rollout, so it takes no tab-specific props.
 */
export default function ArchitectRecommendations({
  sections,
  fallbackSections,
  loading,
  className,
  modelUsed,
  summary,
  effortHours,
}: Props) {
  const isAi = !!sections && sections.length > 0;
  const display = isAi ? sections : fallbackSections;

  const [activeTitle, setActiveTitle] = useState<string | undefined>(display[0]?.title);
  const [page, setPage] = useState(1);

  // Re-anchor the active tab if the section list changes shape (e.g. fallback
  // sections swapped out once the AI narrative arrives).
  useEffect(() => {
    if (!display.some((s) => s.title === activeTitle)) {
      setActiveTitle(display[0]?.title);
      setPage(1);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [display.map((s) => s.title).join('|')]);

  if (loading) {
    return (
      <GlassCard className={cn('space-y-3 animate-pulse', className)}>
        <div className="h-3 w-40 rounded bg-sf-bg-3" />
        <div className="h-4 w-full rounded bg-sf-bg-3" />
        <div className="h-4 w-5/6 rounded bg-sf-bg-3" />
      </GlassCard>
    );
  }

  const activeSection = display.find((s) => s.title === activeTitle) ?? display[0];
  const activePoints = activeSection?.points ?? [];
  const pagedPoints = activePoints.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  function selectTab(title: string) {
    setActiveTitle(title);
    setPage(1);
  }

  return (
    <GlassCard className={className}>
      <div className="flex items-center justify-between gap-3 flex-wrap mb-2">
        <div className="flex items-center gap-2">
          <span className="text-[13px]">🏛️</span>
          <span className="text-xs font-semibold text-sf-text">Architect Recommendations</span>
          <span
            className={cn(
              'px-1.5 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-wide',
              isAi ? 'bg-purple-500/20 text-purple-400' : 'bg-sf-bg-3 text-sf-muted'
            )}
          >
            {isAi ? 'AI' : 'Beta'}
          </span>
        </div>
        {modelUsed && (
          <span className="px-2 py-0.5 rounded-full border border-sf-accent/30 bg-sf-accent/10 text-[10px] font-semibold text-sf-accent">
            Generated by {modelUsed}
          </span>
        )}
      </div>

      {summary && (
        <p className="text-xs text-sf-muted leading-relaxed mb-2">{summary}</p>
      )}

      {effortHours !== undefined && (
        <div className="flex items-center justify-between pt-2 pb-3 border-t border-sf-border/60 mb-1">
          <span className="text-[11px] text-sf-muted">Est. effort to close current gaps</span>
          <span className="text-xs font-semibold text-sf-text">{effortHours > 0 ? `~${effortHours} Hours` : 'None'}</span>
        </div>
      )}

      {display.length === 0 && (
        <p className="text-xs text-sf-muted">No recommendations available yet.</p>
      )}

      {display.length > 0 && (
        <>
          <SegmentedTabs
            items={display.map((s) => ({ id: s.title, label: s.title, count: s.points.length }))}
            active={activeTitle ?? display[0].title}
            onChange={selectTab}
            variant="pill"
            size="sm"
            className="mb-3"
          />

          {activePoints.length === 0 ? (
            <p className="text-xs text-sf-muted">No recommendations in this section.</p>
          ) : (
            <div className="overflow-x-auto rounded-lg border border-sf-border/50">
              <table className="w-full text-left table-fixed">
                <thead>
                  <tr>
                    <th className="w-20 px-2 py-1.5 text-[10px] font-semibold uppercase tracking-wide text-sf-muted border-b border-sf-border/60">
                      Priority
                    </th>
                    <th className="px-2 py-1.5 text-[10px] font-semibold uppercase tracking-wide text-sf-muted border-b border-sf-border/60">
                      Recommendation
                    </th>
                    <th className="w-56 px-2 py-1.5 text-[10px] font-semibold uppercase tracking-wide text-sf-muted border-b border-sf-border/60">
                      Evidence
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {pagedPoints.map((point, i) => (
                    <tr key={i} className={i % 2 ? 'bg-sf-glass-stripe' : ''}>
                      <td className="px-2 py-2 align-top">
                        <Badge variant={PRIORITY_VARIANT[point.priority]}>{point.priority}</Badge>
                      </td>
                      <td className="px-2 py-2 text-xs text-sf-text align-top break-words">{point.text}</td>
                      <td className="px-2 py-2 align-top">
                        {point.evidence && point.evidence.length > 0 ? (
                          <ul className="space-y-0.5">
                            {point.evidence.map((e, ei) => (
                              <li key={ei} className="text-[10px] text-sf-muted italic break-words">
                                “{e}”
                              </li>
                            ))}
                          </ul>
                        ) : (
                          <span className="text-[11px] text-sf-muted">—</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          <Pagination page={page} pageSize={PAGE_SIZE} total={activePoints.length} onChange={setPage} />
        </>
      )}
    </GlassCard>
  );
}
